accounts/urls.py
from django.urls import path
from . import views, forms
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('', views.index_page, name="index"),
    path('signup/', views.signup, name="signup"),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name="accounts/login.html",
            authentication_form=forms.CustomAuthenticationForm
        ),
        name="login"
    ),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup-successful/', views.signup_successful, name="successfulsignup"),
    path(
        'password-change/',
        auth_views.PasswordChangeView.as_view(
            form_class=forms.CustomPasswordChangeForm,
            template_name="accounts/password_change_form.html",
            success_url="password-change-done/",
        ),
        name="password_change"
    ),
    path(
        'password-change/password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"
        ),
        name="password_change_done"
    ),
    path(
        'account-type-change/',
        views.account_type_change,
        name="account_type_change"
    ),
    path(
        'premium-customer-club/',
        views.premium_customer_club,
        name="premium_customer_club"
    ),
    path(
        'account_delete/',
        views.account_delete,
        name="account_delete"
    )
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class PremiumUser(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    is_premium = models.BooleanField('کاربر ویژه', default=False)

    class Meta:
        verbose_name = "نوع حساب کاربری"

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.contrib.auth.password_validation import validate_password
import re
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)


class SignUpForm(forms.Form):
    username = forms.CharField( 
        label="نام کاربری",
        max_length=150,
        min_length=4,
        validators=[
            RegexValidator(
                regex=r"^[\w.@+-]+\Z",
                message="فقط از حروف الفبا و اعداد انگلیسی و نمادهای [@.-_+] استفاده شود.",
                flags=re.A
            )
        ]
    )
    email = forms.EmailField(
        label="ایمیل"
    )
    password = forms.CharField(
        label="گذرواژه",
        widget=forms.PasswordInput
    )
    password_confirmation = forms.CharField(
        label="تکرار گذرواژه",
        widget=forms.PasswordInput
    )

    username.widget.attrs.update({'class': 'form-control'})
    email.widget.attrs.update({'class': 'form-control'})
    password.widget.attrs.update({'class': 'form-control'})
    password_confirmation.widget.attrs.update({'class': 'form-control'})

    def clean_username(self):
        """Prevents the duplication of username."""
        username = self.cleaned_data['username']
        try:
            User.objects.get(username__iexact=username)
        except User.DoesNotExist:
            return username
        raise ValidationError("این نام کاربری قبلا ثبت شده است.")
        
    def clean_email(self):
        """Prevents the duplication of email."""
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise ValidationError("این آدرس ایمیل قبلا ثبت شده است.")
    
    def clean_password(self):
        """Validates the password through the password validators"""
        password = self.cleaned_data['password']
        try:
            username = self.cleaned_data['username']
        except:
            username = None
        try:
            email = self.cleaned_data['email']
        except:
            email = None
        user = User(
            username=username,
            email=email,
        )
        validate_password(password, user=user)
        return password

    def clean_password_confirmation(self):
        """Checks the similarity of the password_confirmation field to the password field"""
        password_confirmation = self.cleaned_data['password_confirmation']
        try:
            password = self.cleaned_data['password']
        except:
            password = None
        if password_confirmation != password:
            raise ValidationError("تکرار گذرواژه صحیح نمی‌باشد.")
        return password_confirmation


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})


class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = "گذرواژه فعلی"
        self.fields['new_password1'].label = "گذرواژه جدید"
        self.fields['new_password2'].label = "تکرار گذرواژه جدید"
        self.fields['old_password'].widget.attrs.update({'class': 'form-control'})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control'})
        self.error_messages["password_incorrect"] = "گذرواژه اشتباه است."

accounts/views.py
from django.shortcuts import render
from . import forms
from .models import PremiumUser
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


def index_page(request):
    """Renders the index page."""
    return render(request, 'accounts/index.html')


def signup(request):
    if request.method == "POST":
        signup_form = forms.SignUpForm(request.POST)
        if signup_form.is_valid():
            User.objects.create_user(
                request.POST['username'],
                email = request.POST['email'],
                password = request.POST['password']
            )
            return HttpResponseRedirect(reverse("accounts:successfulsignup"))
    else:
        signup_form = forms.SignUpForm()
    context = {
        "signup_form": signup_form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    return render(request, "accounts/login.html")


def signup_successful(request):
    return render(request, "accounts/successful_signup.html")


@login_required
def account_type_change(request):
    user = PremiumUser.objects.get(user=request.user.pk)
    if request.method == "POST":
        if user.is_premium:
            user.is_premium = False
        else:
            user.is_premium = True
        user.save()
    context = {"acctype": user.is_premium,}
    return render(request, "accounts/account_type_change_form.html", context)


def premium_access(user):
    u = PremiumUser.objects.get(user=user.pk)
    return u.is_premium

@login_required
@user_passes_test(premium_access)
def premium_customer_club(request):
    return render(request, "accounts/premium_customer_club.html")

@login_required
def account_delete(request):
    if request.method == "POST":
        user = User.objects.get(username=request.user.username)
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse("accounts:login"))
    return render(request, "accounts/account_delete.html")

accounts/templates/accounts/account_delete.html
{% extends "base.html" %}

{% block body %}
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <div class="text-bg-danger border border-2 rounded border-dark" style="margin: 3% 16% 0px;">
      <div class="p-3">
          <h3 class="text-center">فرم حذف حساب کاربری</h3>
      </div>

      <div class="p-4 border-top border-dark">
        <div class="d-grid gap-2 mt-5">
          <button type="submit" class="btn btn-light">حذف حساب کاربری</button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}

accounts/templates/accounts/account_type_change_form.html
{% extends "base.html" %}

{% block body %}
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <div class="text-bg-danger border border-2 rounded border-dark" style="margin: 3% 16% 0px;">
      <div class="p-3">
          <h3 class="text-center">فرم تغییر نوع حساب کاربری</h3>
      </div>

      <div class="p-4 border-top border-dark">
        <p class="text-center fs-4 text-danger-emphasis">شما یک کاربر <span class="text-success-emphasis fw-bolder">{% if acctype %}ویژه{% else %}عادی{% endif %}</span> هستید.</p>

        <div class="d-grid gap-2 mt-5">
          <button type="submit" class="btn btn-light">تغییر نوع حساب کاربری به <span class="fw-bolder">{% if acctype %}عادی{% else %}ویژه{% endif %}</span></button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block body %}
  {% if request.user.is_authenticated %}
    {% include "authenticateduser_nav.html" %}
  {% else %}
    {% include "anonymoususer_nav.html" %}
  {% endif %}
    
  <div class="position-fixed" style="height: 80vh; width: 100vw; display: flex; justify-content: center; align-items: center;">
    <div class="text-center text-primary-emphasis">
      <h1>سیستم احراز هویت<br>و<br>سطح دسترسی</h1>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}


{% block body %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    
    <div class="text-bg-light border border-2 rounded border-dark" style="margin: 3% 20% 0px;">
      <div class="p-3">
        <h3 class="text-center">فرم ورود</h3>
      </div>

      <div class="p-4 border-top border-dark">
        {% for field in form %}
          <div class="row mb-3">
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              <ul class="form-text text-danger">
                {% for error in field.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endfor %}
        
        {% if form.non_field_errors  %}
          <div class="form-text text-bg-danger rounded p-2">
            {{ form.non_field_errors }}
          </div>
        {% endif %}

        <div class="d-grid gap-2 mt-4">
          <button type="submit" class="btn btn-dark">ورود</button>
        </div>
      </div>
    </div>
  </form>

  {% if request.user.is_authenticated %}
    <script>window.location.href='{% url "accounts:index" %}';</script>
  {% endif %}
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block body %}
  <div class="position-fixed" style="height: 80vh; width: 100vw; display: flex; justify-content: center; align-items: center;">
    <div class="text-center text-bg-success p-4 rounded">
      <h3>تغییر رمز عبور موفقیت آمیز بود.</h3>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}


{% block body %}
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <div class="text-bg-secondary border border-2 rounded border-warning" style="margin: 3% 16% 0px;">
      <div class="p-3">
          <h3 class="text-center text-warning">فرم تغییر رمز عبور</h3>
      </div>

      <div class="p-4 border-top border-dark">
        {% for field in form %}
          <div class="row mb-3">
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.id_for_label == "id_new_password1" %}
                <div class="form-text">
                  <p class="text-primary-emphasis small">رمز عبور باید حداقل 8 کاراکتر و نباید تنها شامل اعداد باشد. همچنین رمز عبور نباید تشابه بالایی با نام کاربری یا ایمیل‌تان داشته باشد. همچنین رمز عبور نباید جزو رمز عبورهای رایج باشد.</p>
                </div>
              {% endif %}
              <ul class="form-text text-info">
                {% for error in field.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endfor %}
        
        {% if form.non_field_errors  %}
          <div class="form-text text-bg-info rounded p-2">
            {{ form.non_field_errors }}
          </div>
        {% endif %}

        <div class="d-grid gap-2 mt-4">
          <button type="submit" class="btn btn-warning">تغییر رمز عبور</button>
        </div>
      </div>
    </div>
  </form>

{% endblock %}

accounts/templates/accounts/premium_customer_club.html
{% extends "base.html" %}


{% block body %}
  <div class="position-fixed" style="height: 80vh; width: 100vw; display: flex; justify-content: center; align-items: center;">
    <div class="text-center text-success">
      <h1>به صفحه باشگاه مشتریان ویژه خوش آمدید.</h1>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}


{% block body %}
  <form action="" method="post" novalidate>
    {% csrf_token %}

    <div class="bg-warning border border-2 rounded border-dark" style="margin: 3% 20% 0px;">
      <div class="p-3">
        <h3 class="text-center">فرم ثبت‌نام</h3>
      </div>

      <div class="p-4 border-top border-dark">
        {% for field in signup_form %}
          <div class="row mb-3">
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.id_for_label == "id_password" %}
                <div class="form-text">
                  <p class="text-primary-emphasis small">گذرواژه باید حداقل 8 کاراکتر و نباید تنها شامل اعداد باشد. همچنین گذرواژه نباید تشابه بالایی با نام کاربری یا ایمیل‌تان داشته باشد و نیز گذرواژه نباید جزو گذرواژه‌های رایج باشد.</p>
                </div>
              {% endif %}
              <ul class="form-text text-danger-emphasis">
                {% for error in field.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% endfor %}

        <div class="d-grid gap-2 mt-4">
          <button type="submit" class="btn btn-dark">ثبت‌نام</button>
        </div>
      </div>
    </div>
  </form>

  {% if request.user.is_authenticated %}
    <script>window.location.href='{% url "accounts:index" %}';</script>
  {% endif %}
{% endblock %}

accounts/templates/accounts/successful_signup.html
{% extends "base.html" %}

{% if request.user.is_authenticated %}
  <script>window.location.href='{% url "accounts:index" %}';</script>
{% endif %}

{% block body %}
  <div class="position-fixed" style="height: 80vh; width: 100vw; display: flex; justify-content: center; align-items: center;">
    <div class="text-center text-bg-success p-4 rounded">
      <h3>ثبت‌نام شما موفقیت آمیز بود.</h3>
      <h3>برای ورود به حساب کاربری خود به صفحه ورود مراجعه فرمایید.</h3>
    </div>
  </div>
{% endblock %}

templates/anonymoususer_nav.html
<ul class="nav nav-tabs justify-content-center bg-primary">
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url 'accounts:index' %}">صفحه اصلی</a>
  </li>
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url 'accounts:login' %}">ورود</a>
  </li>
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url 'accounts:signup' %}">ثبت‌نام</a>
  </li>
</ul>

templates/authenticateduser_nav.html
<ul class="nav nav-tabs justify-content-center bg-primary">
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url 'accounts:index' %}">صفحه اصلی</a>
  </li>
  <li class="nav-item dropdown dropdown-center">
    <a class="nav-link dropdown-toggle link-light" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">حساب کاربری</a>
    <ul class="dropdown-menu bg-primary text-end">
      <li><a class="dropdown-item text-warning" href="{% url 'accounts:password_change' %}">تغییر گذرواژه</a></li>
      <li><a class="dropdown-item text-warning" href="{% url 'accounts:account_type_change' %}">تغییر نوع حساب کاربری</a></li>
      <li><a class="dropdown-item text-warning" href="{% url 'accounts:account_delete' %}">حذف حساب کاربری</a></li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <form action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn text-warning">خروج از حساب کاربری</button>
        </form>
      </li>
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url 'accounts:premium_customer_club' %}">باشگاه کاربران ویژه</a>
  </li>
</ul>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Sina Arasteh">
  <meta name="generator" content="Django framework">
  <meta name="application-name" content="Authentication & Authorization system">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-DQvkBjpPgn7RC31MCQoOeC9TI2kdqa4+BSgNMNj8v77fdC77Kj5zpWFTJaaAoMbC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.4/dist/js/bootstrap.bundle.min.js" integrity="sha384-YUe2LzesAfftltw+PEaao2tjU/QATaW/rOitAq67e0CT0Zi2VVRL0oC4+gAaeBKu" crossorigin="anonymous" defer></script>

  <title>سیستم احراز هویت و سطح دسترسی</title>
</head>
<body class="bg-info-subtle">
  <div class="position-fixed z-1" style="bottom: 4%; left: 2%;">
    <a href="https://github.com/Sina-Arasteh/authentication-authorization-in-django" target="_blank">
      <i class="bi bi-github fs-1 text-black"></i>
    </a>
  </div>

  {% if request.user.is_authenticated %}
    {% include "authenticateduser_nav.html" %}
  {% else %}
    {% include "anonymoususer_nav.html" %}
  {% endif %}

  {% block body %}{% endblock %}

  {% if request.user.is_authenticated %}
    <h4 class="position-fixed text-dark" style="bottom: 4%; right: 2%;">نام کاربری: {{ request.user.username }}</h4>
  {% endif %}
</body>
</html>